name = "landing-page"
main = "src/worker.js"
compatibility_date = "2024-01-01"

[vars]
MAILGUN_DOMAIN = "mailgun.developir.net"
MAILGUN_EMAIL = "drew@developir.net"

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true


[env.production]
workers_dev = true
route = "developir.net/*"